# Docs for Azure Functions GitHub Actions:
# https://github.com/Azure/functions-action

name: Build and deploy Python project to Azure Function App - infobric-headcount-monitor

on:
  push:
    branches:
      - azure-function
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'
  PYTHON_VERSION: '3.11'

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Setup Python version
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'


      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      # Optional: add tests here


      - name: Zip artifact for deployment
        run: |
          zip release.zip ./* -r \
          -x "*.git*" \
          -x "venv/*" \
          -x ".venv/*" \
          -x "__pycache__/*"


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip



  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app


      - name: Extract artifact
        run: |
          unzip release.zip
          rm release.zip


      - name: Deploy to Azure Functions
        uses: Azure/functions-action@v1

        with:
          app-name: 'infobric-headcount-monitor'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}

          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A95301DC4A2C4B2C82E688110C3F95DB }}

          scm-do-build-during-deployment: true
          enable-oryx-build: true
          sku: 'flexconsumption'